# This is a basic workflow to help you get started with Actions

name: Location CI

# Controls when the workflow will run
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install 
    
